// initialize to defaults
let EYE_EXERCISE_DURATION = DEFAULT_EYE_EXERCISE_DURATION;
let LONG_BREAK_DURATION = DEFAULT_LONG_BREAK_DURATION;
let EYE_EXERCISE_INTERVAL = DEFAULT_EYE_EXERCISE_INTERVAL;
let LONG_BREAK_INTERVAL = DEFAULT_LONG_BREAK_INTERVAL;
let sound = true;
